apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prometheus-cr.fullname" . }}-proxy
  labels:
    {{- include "prometheus-cr.labels" . | nindent 4 }}
type: Opaque
data:
  session_secret: "{{ .Values.sessionSecret | b64enc }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prometheus-cr.fullname" . }}-htpasswd
  labels:
    {{- include "prometheus-cr.labels" . | nindent 4 }}
type: Opaque
data:
  auth: "{{ htpasswd .Values.basicAuthUsername .Values.basicAuthPassword  | b64enc }}"
