apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "rosa-federated-prometheus.fullname" . }}-cluster
  labels:
    {{- include "rosa-federated-prometheus.labels" . | nindent 4 }}
    prometheus: {{ .Release.Name }}-prometheus-cr
spec:
  endpoints:
  - interval: 30s
    scrapeTimeout: 30s
    port: web
    path: /federate
    honorLabels: true
    params:
      'match[]':
        - '{job!=""}'
    scheme: https
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    tlsConfig:
      caFile: /etc/prometheus/configmaps/openshift-service-ca.crt/service-ca.crt
      serverName: prometheus-k8s.openshift-monitoring.svc.cluster.local
  namespaceSelector:
    matchNames:
    - openshift-monitoring
  selector:
    matchLabels:
      app.kubernetes.io/instance: k8s
