{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rosa-aws-prometheus.serviceAccountName" . }}
  labels:
    {{- include "rosa-aws-prometheus.labels" . | nindent 4 }}
{{- if .Values.aws.roleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.aws.roleArn }}
{{- end }}
{{- end }}
