apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
  labels:
    {{- include "aro-clf-am.labels" . | nindent 4 }}
spec:
  outputs:
    - name: fluentbit
      type: fluentdForward
      url: 'tcp://{{ include "aro-clf-am.fullname" . }}.{{ .Release.Namespace }}:24224'
  pipelines:
    - name: forward-to-fluentbit
      inputRefs:
        {{- if .Values.clf.infrastructure }}
        - infrastructure
        {{- end }}
        {{- if .Values.clf.application }}
        - application
        {{- end }}
        {{- if .Values.clf.audit }}
        - audit
        {{- end }}
      outputRefs:
        - fluentbit
