{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aro-clf-am.serviceAccountName" . }}
  labels:
    {{- include "aro-clf-am.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "aro-clf-am.serviceAccountName" . }}
rules:
- apiGroups: [ "" ]
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - watch
  - list
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "aro-clf-am.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "aro-clf-am.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "aro-clf-am.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
