apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grafana-cr.fullname" . }}-proxy
  labels:
    {{- include "grafana-cr.labels" . | nindent 4 }}
type: Opaque
stringData:
  session_secret: "{{ .Values.sessionSecret }}"
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "grafana-cr.fullname" . }}-creds
stringData:
  GF_SECURITY_ADMIN_PASSWORD: "{{ .Values.basicAuthPassword }}"
  GF_SECURITY_ADMIN_USER: "{{ .Values.basicAuthUsername }}"
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grafana-cr.fullname" . }}-htpasswd
  labels:
    {{- include "grafana-cr.labels" . | nindent 4 }}
type: Opaque
data:
  auth: "{{ htpasswd .Values.basicAuthUsername .Values.basicAuthPassword  | b64enc }}"
---