apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  # namespace: openshift-dbaas-operator
  name: {{ include "redhat-dbaas-operator.fullname" . }}
  labels:
    {{- include "redhat-dbaas-operator.labels" . | nindent 4 }}
spec:
