apiVersion: v1
kind: Service
metadata:
  name: {{ include "rosa-aws-prometheus.fullname" . }}
  labels:
    {{- include "rosa-aws-prometheus.labels" . | nindent 4 }}
spec:
  ports:
    - protocol: TCP
      port: 8005
      targetPort: 8005
  selector:
    {{- include "rosa-aws-prometheus.selectorLabels" . | nindent 4 }}
