---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aro-thanos-af.serviceAccountName" . }}-af-creds
  namespace: {{ .Release.Namespace }}
stringData:
  store-secret.yaml: |
    type: AZURE
    config:
      storage_account: "{{ .Values.aro.storageAccount }}"
      storage_account_key: "{{ .Values.aro.storageAccountKey }}"
      container: "{{ .Values.aro.storageContainer }}"
      max_retries: 0
