{{- $clusterPullSecret := lookup "v1" "Secret" "openshift-config" "pull-secret" -}}
{{- $dockerConfigJson := get ((include "aro-pull-secret.dummy" .) | fromJson).data ".dockerconfigjson" | b64dec }}
{{- if not (empty $clusterPullSecret) -}}
{{- $dockerConfigJson = get ($clusterPullSecret.data) ".dockerconfigjson" | b64dec }}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: pull-secret
  namespace: openshift-config
  labels:
    {{- include "aro-pull-secret.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ merge ($dockerConfigJson | fromJson) (.Values.pullSecret | fromJson) | toJson | b64enc }}
