subscriptions:
  - name: cluster-logging
    channel: stable
    installPlanApproval: Automatic
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    namespace: openshift-logging
    startingCSV: cluster-logging.5.3.3-4
  - name: elasticsearch-operator
    channel: stable
    installPlanApproval: Automatic
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    namespace: openshift-operators-redhat
    startingCSV: elasticsearch-operator.5.3.3-4

operatorGroups:
  - name: openshift-logging
    namespace: openshift-logging
    targetNamespace: openshift-logging
  - name: openshift-operators-redhat
    namespace: openshift-operators-redhat
    targetNamespace: all

