# kubectl create secret generic fluentbit-secrets -n azure-log-forwarder \
#       --from-literal=WorkspaceId=$WORKSPACE_ID \
#       --from-literal=SharedKey=$SHARED_KEY

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aro-clf-am.fullname" . }}
  labels:
    {{- include "aro-clf-am.labels" . | nindent 4 }}
type: Opaque
data:
  WorkspaceId: {{ .Values.azure.workspaceId | b64enc }}
  SharedKey: {{ .Values.azure.sharedKey | b64enc }}
