apiVersion: v1
kind: Service
metadata:
  name: {{ include "aro-clf-am.fullname" . }}
  labels:
    {{- include "aro-clf-am.labels" . | nindent 4 }}
    kubernetes.io/cluster-service: "true"
spec:
  ports:
    - protocol: TCP
      port: 24224
      targetPort: 24224
  selector:
    {{- include "aro-clf-am.selectorLabels" . | nindent 4 }}
