nameOverride: ""
fullnameOverride: ""

replicaCount: 2
version: v2.8.0
basicAuthUsername: "internal"
# Change these two fields
sessionSecret: "112RXXaWl7wUQiSdXUMrUya7kN5gOZmHc0s202bKqAw"
basicAuthPassword: "KgX1EUO3eQOBr1u9Df5B6XEhfxWGKaBKMhEa1ALQvu6"
