subscriptions:
  - name: dbaas-operator
    channel: alpha
    installPlanApproval: Automatic
    source: dbaas-operator
    sourceNamespace: openshift-dbaas-operator
    namespace: openshift-dbaas-operator
    startingCSV: dbaas-operator.v0.2.0

operatorGroups:
  - name: dbaas-operator-group
    namespace: openshift-dbaas-operator
    targetNamespace: ~

catalogSources:
  - name: dbaas-operator
    namespace: redhat-dbaas-operator
    sourceType: grpc
    image:  quay.io/osd-addons/dbaas-operator-index@sha256:f7bd64974ab6c2d4e055fdd5de7939961db2306e28282350d34c9ddb85bbb50c
    displayName: DBaaS Operator
    publisher: Red Hat
