apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: {{ include "alertmanager-cr.fullname" . }}
spec:
  securityContext: {}
  replicas: 3
  configSecret: {{ include "alertmanager-cr.fullname" . }}-config
