apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alertmanager-cr.fullname" . }}-config
  labels:
    {{- include "alertmanager-cr.labels" . | nindent 4 }}
stringData:
  alertmanager.yaml: |
{{ .Values.config | toYaml | nindent 4 }}
