apiVersion: v1
kind: Service
metadata:
  name: {{ include "alertmanager-cr.fullname" . }}
  labels:
    {{- include "alertmanager-cr.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: web
    port: 9093
    protocol: TCP
    targetPort: web
  selector:
    alertmanager: {{ include "alertmanager-cr.fullname" . }}
